### ISSUE TITLE
[improvement] Using snakecase for the name of the modules

### ISSUE THREAD

**Issue by kikocorreoso** [aariste/AEMET-Python#2]
Hi,

the main package `Aemet.py` should be renamed to `aemet.py` in order to avoid misunderstandings and to respect PEP8.

KR,

**Comment by aariste** [comment]
Done! Thanks!

**Comment by kikocorreoso** [comment]
Thanks.

Just for curiosity, as it is a change in the API and not compatible with previous versions, do you plan to make a new V2.0.0 PyPI release?

**Comment by aariste** [comment]
No, I'm not maintaining this.

**Comment by kikocorreoso** [comment]
Cool, thanks.

So I suppose it is ok if I create an `AEMET-python3` and upload that version to PyPI.

I think it has value to have a Python3 package to download Aemet data without the need to use the API.
